/*
 * Copyright 2026 i-Bridge bv
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.hop.databases.hopsourcemodel;

import org.apache.hop.core.Const;
import org.apache.hop.core.database.BaseDatabaseMeta;
import org.apache.hop.core.database.DatabaseMeta;
import org.apache.hop.core.database.DatabaseMetaPlugin;
import org.apache.hop.core.database.IDatabase;
import org.apache.hop.core.gui.plugin.GuiPlugin;
import org.apache.hop.core.row.IValueMeta;
import org.apache.hop.core.util.Utils;

/**
 * Hop connection type for the thin hop-hsm JDBC driver (free SQL against Hop Server source model
 * services).
 *
 * <p>Connection fields map to {@code jdbc:hop-hsm://host:port/[service]}:
 *
 * <ul>
 *   <li><strong>Host</strong> — Hop Server hostname
 *   <li><strong>Port</strong> — Hop Server HTTP port (default {@value #DEFAULT_PORT})
 *   <li><strong>Database name</strong> — optional default Source model service (JDBC schema)
 *   <li><strong>Username / password</strong> — Hop Server credentials (passed as JDBC properties)
 * </ul>
 *
 * <p>Read-only virtual views over named source model services; DDL and writes are not supported.
 */
@DatabaseMetaPlugin(
    type = "HOPSOURCEMODEL",
    typeDescription = "Apache Hop Source Model",
    image = "source-model.svg",
    documentationUrl =
        "https://github.com/ProjectDataHopper/hopper-edw/blob/main/hop-hsm-jdbc/README.md")
@GuiPlugin(id = "GUI-HopSourceModelDatabaseMeta")
public class HopSourceModelDatabaseMeta extends BaseDatabaseMeta implements IDatabase {

  /** Common Hop Server listen port used in tutorials and hop-server defaults. */
  public static final int DEFAULT_PORT = 8080;

  public static final String DRIVER_CLASS = "org.apache.hop.hsm.jdbc.HopHsmJdbcDriver";

  public static final String JDBC_PREFIX = "jdbc:hop-hsm://";

  @Override
  public int[] getAccessTypeList() {
    return new int[] {DatabaseMeta.TYPE_ACCESS_NATIVE};
  }

  @Override
  public int getDefaultDatabasePort() {
    if (getAccessType() == DatabaseMeta.TYPE_ACCESS_NATIVE) {
      return DEFAULT_PORT;
    }
    return -1;
  }

  @Override
  public String getDriverClass() {
    return DRIVER_CLASS;
  }

  @Override
  public String getURL(String hostname, String port, String databaseName) {
    StringBuilder url = new StringBuilder(JDBC_PREFIX);
    url.append(Utils.isEmpty(hostname) ? "localhost" : hostname);
    if (!Utils.isEmpty(port)) {
      url.append(':').append(port);
    }
    // Optional default Source model service (= JDBC schema)
    if (!Utils.isEmpty(databaseName)) {
      url.append('/').append(databaseName);
    }
    return url.toString();
  }

  @Override
  public String getExtraOptionIndicator() {
    return "?";
  }

  @Override
  public String getExtraOptionSeparator() {
    return "&";
  }

  @Override
  public String getExtraOptionValueSeparator() {
    return "=";
  }

  @Override
  public String getExtraOptionsHelpText() {
    return "https://github.com/ProjectDataHopper/hopper-edw/blob/main/hop-hsm-jdbc/README.md";
  }

  @Override
  public void addDefaultOptions() {
    setSupportsBooleanDataType(true);
    setSupportsTimestampDataType(true);
  }

  @Override
  public boolean isSupportsBooleanDataType() {
    return true;
  }

  @Override
  public boolean isSupportsTimestampDataType() {
    return true;
  }

  @Override
  public boolean isSupportsSchemas() {
    // Each Source model service is exposed as a JDBC schema.
    return true;
  }

  @Override
  public boolean isSupportsCatalogs() {
    return false;
  }

  @Override
  public boolean isSupportsViews() {
    // JSON / pipeline feeds appear as VIEW in DatabaseMetaData.
    return true;
  }

  @Override
  public boolean isSupportsSynonyms() {
    return false;
  }

  @Override
  public boolean isSupportsTransactions() {
    return false;
  }

  @Override
  public boolean isSupportsBitmapIndex() {
    return false;
  }

  @Override
  public boolean isSupportsSequences() {
    return false;
  }

  @Override
  public boolean isSupportsAutoInc() {
    return false;
  }

  @Override
  public boolean isSupportsAutoGeneratedKeys() {
    return false;
  }

  @Override
  public boolean isFetchSizeSupported() {
    return false;
  }

  @Override
  public boolean isRequiringTransactionsOnQueries() {
    return false;
  }

  @Override
  public boolean isSupportsGetBlob() {
    return false;
  }

  @Override
  public boolean isSupportsSetCharacterStream() {
    return false;
  }

  @Override
  public boolean isSupportsBatchUpdates() {
    return false;
  }

  @Override
  public boolean IsSupportsErrorHandlingOnBatchUpdates() {
    return false;
  }

  @Override
  public String getStartQuote() {
    return "\"";
  }

  @Override
  public String getEndQuote() {
    return "\"";
  }

  @Override
  public String getLimitClause(int nrRows) {
    return " LIMIT " + nrRows;
  }

  @Override
  public String getSqlQueryFields(String tableName) {
    return "SELECT * FROM " + tableName + " LIMIT 0";
  }

  @Override
  public String getSqlTableExists(String tableName) {
    return getSqlQueryFields(tableName);
  }

  @Override
  public String getSqlColumnExists(String columnname, String tableName) {
    return "SELECT " + columnname + " FROM " + tableName + " LIMIT 0";
  }

  @Override
  public String getAddColumnStatement(
      String tableName,
      IValueMeta v,
      String tk,
      boolean useAutoIncrement,
      String pk,
      boolean semicolon) {
    // Read-only virtualization over Hop Server source models.
    return null;
  }

  @Override
  public String getModifyColumnStatement(
      String tableName,
      IValueMeta v,
      String tk,
      boolean useAutoIncrement,
      String pk,
      boolean semicolon) {
    return null;
  }

  @Override
  public String getDropColumnStatement(
      String tableName,
      IValueMeta v,
      String tk,
      boolean useAutoIncrement,
      String pk,
      boolean semicolon) {
    return null;
  }

  @Override
  public String getFieldDefinition(
      IValueMeta v,
      String tk,
      String pk,
      boolean useAutoIncrement,
      boolean addFieldName,
      boolean addCr) {
    // DDL is not used against hop-hsm; keep a reasonable Calcite-style mapping for tooling.
    StringBuilder retval = new StringBuilder();
    String fieldname = v.getName();
    if (addFieldName) {
      retval.append(fieldname).append(' ');
    }

    switch (v.getType()) {
      case IValueMeta.TYPE_TIMESTAMP, IValueMeta.TYPE_DATE -> retval.append("TIMESTAMP");
      case IValueMeta.TYPE_BOOLEAN -> retval.append("BOOLEAN");
      case IValueMeta.TYPE_NUMBER, IValueMeta.TYPE_BIGNUMBER -> {
        int length = v.getLength();
        int precision = v.getPrecision();
        if (length > 0) {
          if (precision > 0) {
            retval.append("DECIMAL(").append(length).append(',').append(precision).append(')');
          } else {
            retval.append("DECIMAL(").append(length).append(')');
          }
        } else {
          retval.append("DOUBLE");
        }
      }
      case IValueMeta.TYPE_INTEGER -> {
        int length = v.getLength();
        if (length > 0 && length <= 9) {
          retval.append("INTEGER");
        } else {
          retval.append("BIGINT");
        }
      }
      case IValueMeta.TYPE_STRING -> {
        int length = v.getLength();
        if (length < 1 || length >= DatabaseMeta.CLOB_LENGTH) {
          retval.append("VARCHAR");
        } else {
          retval.append("VARCHAR(").append(length).append(')');
        }
      }
      case IValueMeta.TYPE_BINARY -> retval.append("VARBINARY");
      default -> retval.append("VARCHAR");
    }

    if (addCr) {
      retval.append(Const.CR);
    }
    return retval.toString();
  }

  @Override
  public String[] getReservedWords() {
    return new String[] {
      "ALL",
      "AND",
      "AS",
      "ASC",
      "BETWEEN",
      "BY",
      "CASE",
      "CAST",
      "CROSS",
      "DESC",
      "DISTINCT",
      "ELSE",
      "END",
      "EXCEPT",
      "EXISTS",
      "FALSE",
      "FROM",
      "FULL",
      "GROUP",
      "HAVING",
      "IN",
      "INNER",
      "INTERSECT",
      "IS",
      "JOIN",
      "LEFT",
      "LIKE",
      "LIMIT",
      "NOT",
      "NULL",
      "ON",
      "OR",
      "ORDER",
      "OUTER",
      "RIGHT",
      "SELECT",
      "THEN",
      "TRUE",
      "UNION",
      "USING",
      "WHEN",
      "WHERE",
      "WITH"
    };
  }
}
