-- Generated by Hop Data Vault schema remediation
-- Review before running on each DTAP environment.
-- Workflow companion executes one SQL action per target table.

-- Connection: Vault  Table: sat_customer_address
ALTER TABLE sat_customer_address ADD COLUMN address_line1_KTL VARCHAR(75);
UPDATE sat_customer_address SET address_line1_KTL=address_line1;
ALTER TABLE sat_customer_address DROP COLUMN address_line1;
ALTER TABLE sat_customer_address RENAME address_line1_KTL TO address_line1;

;

-- Connection: Vault  Table: customer_360_bv
ALTER TABLE customer_360_bv ADD COLUMN cust_address_KTL VARCHAR(75);
UPDATE customer_360_bv SET cust_address_KTL=cust_address;
ALTER TABLE customer_360_bv DROP COLUMN cust_address;
ALTER TABLE customer_360_bv RENAME cust_address_KTL TO cust_address;

;

-- Connection: Vault  Table: d_customer
ALTER TABLE d_customer ADD COLUMN cust_address_KTL VARCHAR(75);
UPDATE d_customer SET cust_address_KTL=cust_address;
ALTER TABLE d_customer DROP COLUMN cust_address;
ALTER TABLE d_customer RENAME cust_address_KTL TO cust_address;

;

