/*
 * Copyright 2026 i-Bridge bv
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.hop.hsm.jdbc;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.sql.SQLWarning;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/** Executes free SQL via the Hop Server sourceModelData servlet. */
public class HopHsmJdbcStatement implements Statement {

  private final HopHsmJdbcConnection connection;
  private boolean closed;
  private int maxRows;
  private ResultSet current;
  private int updateCount = -1;

  HopHsmJdbcStatement(HopHsmJdbcConnection connection) {
    this.connection = connection;
    this.maxRows = connection.config().rowLimit();
  }

  @Override
  public ResultSet executeQuery(String sql) throws SQLException {
    connection.checkOpen();
    checkOpen();
    int limit = maxRows > 0 ? maxRows : connection.config().rowLimit();
    Map<String, Object> response = connection.http().query(connection.requireSchema(), sql, limit);
    current = HopHsmJdbcResultSet.fromQueryResponse(this, response);
    updateCount = -1;
    return current;
  }

  @Override
  public boolean execute(String sql) throws SQLException {
    executeQuery(sql);
    return true;
  }

  @Override
  public int executeUpdate(String sql) throws SQLException {
    throw new SQLFeatureNotSupportedException("hop-hsm is read-only");
  }

  @Override
  public void close() throws SQLException {
    closed = true;
    if (current != null) {
      current.close();
      current = null;
    }
  }

  void checkOpen() throws SQLException {
    if (closed) {
      throw new SQLException("Statement is closed");
    }
  }

  @Override
  public int getMaxFieldSize() {
    return 0;
  }

  @Override
  public void setMaxFieldSize(int max) {}

  @Override
  public int getMaxRows() {
    return maxRows;
  }

  @Override
  public void setMaxRows(int max) {
    this.maxRows = Math.max(0, max);
  }

  @Override
  public void setEscapeProcessing(boolean enable) {}

  @Override
  public int getQueryTimeout() {
    return 0;
  }

  @Override
  public void setQueryTimeout(int seconds) {}

  @Override
  public void cancel() {}

  @Override
  public SQLWarning getWarnings() {
    return null;
  }

  @Override
  public void clearWarnings() {}

  @Override
  public void setCursorName(String name) {}

  @Override
  public ResultSet getResultSet() {
    return current;
  }

  @Override
  public int getUpdateCount() {
    return updateCount;
  }

  @Override
  public boolean getMoreResults() {
    return false;
  }

  @Override
  public void setFetchDirection(int direction) {}

  @Override
  public int getFetchDirection() {
    return ResultSet.FETCH_FORWARD;
  }

  @Override
  public void setFetchSize(int rows) {}

  @Override
  public int getFetchSize() {
    return 0;
  }

  @Override
  public int getResultSetConcurrency() {
    return ResultSet.CONCUR_READ_ONLY;
  }

  @Override
  public int getResultSetType() {
    return ResultSet.TYPE_FORWARD_ONLY;
  }

  @Override
  public void addBatch(String sql) throws SQLException {
    throw new SQLFeatureNotSupportedException();
  }

  @Override
  public void clearBatch() {}

  @Override
  public int[] executeBatch() throws SQLException {
    throw new SQLFeatureNotSupportedException();
  }

  @Override
  public Connection getConnection() {
    return connection;
  }

  @Override
  public boolean getMoreResults(int current) {
    return false;
  }

  @Override
  public ResultSet getGeneratedKeys() throws SQLException {
    throw new SQLFeatureNotSupportedException();
  }

  @Override
  public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
    throw new SQLFeatureNotSupportedException();
  }

  @Override
  public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
    throw new SQLFeatureNotSupportedException();
  }

  @Override
  public int executeUpdate(String sql, String[] columnNames) throws SQLException {
    throw new SQLFeatureNotSupportedException();
  }

  @Override
  public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
    return execute(sql);
  }

  @Override
  public boolean execute(String sql, int[] columnIndexes) throws SQLException {
    return execute(sql);
  }

  @Override
  public boolean execute(String sql, String[] columnNames) throws SQLException {
    return execute(sql);
  }

  @Override
  public int getResultSetHoldability() {
    return 0;
  }

  @Override
  public boolean isClosed() {
    return closed;
  }

  @Override
  public void setPoolable(boolean poolable) {}

  @Override
  public boolean isPoolable() {
    return false;
  }

  @Override
  public void closeOnCompletion() {}

  @Override
  public boolean isCloseOnCompletion() {
    return false;
  }

  @Override
  public <T> T unwrap(Class<T> iface) throws SQLException {
    if (iface.isInstance(this)) {
      return iface.cast(this);
    }
    throw new SQLException("Not a wrapper for " + iface);
  }

  @Override
  public boolean isWrapperFor(Class<?> iface) {
    return iface.isInstance(this);
  }

  /** Shared helpers for building simple list ResultSets from metadata responses. */
  static List<Object[]> parseObjectRows(List<Object> tables, String... keys) {
    List<Object[]> rows = new ArrayList<>();
    if (tables == null) {
      return rows;
    }
    for (Object o : tables) {
      Map<String, Object> m = HsmJson.asObject(o);
      if (m == null) {
        continue;
      }
      Object[] row = new Object[keys.length];
      for (int i = 0; i < keys.length; i++) {
        row[i] = m.get(keys[i]);
      }
      rows.add(row);
    }
    return rows;
  }
}
