-- Generated by Data Hopper EDW schema remediation
-- Review before running on each DTAP environment.
-- Workflow companion executes one SQL action per target table.

-- Connection: Vault  Table: sat_customer_address
CREATE TABLE sat_customer_address
(
customer_hk VARCHAR(63)
,
address_line1 VARCHAR(75)
,
city VARCHAR(50)
,
postal_code VARCHAR(10)
,
x_record_source VARCHAR(100)
,
x_load_ts TIMESTAMP
,
PRIMARY KEY (customer_hk, x_load_ts),
CONSTRAINT fk_sat_customer_address_hub_customer FOREIGN KEY (customer_hk) REFERENCES hub_customer (customer_hk))
;

