-- Generated by Hop Data Vault schema remediation
-- Review before running on each DTAP environment.
-- Workflow companion executes one SQL action per target table.

-- Connection: Vault  Table: sat_customer_contact
CREATE TABLE sat_customer_contact
(
customer_hk VARCHAR(63)
,
email VARCHAR(50)
,
phone VARCHAR(20)
,
x_record_source VARCHAR(100)
,
x_load_ts TIMESTAMP
,
PRIMARY KEY (customer_hk, x_load_ts),
CONSTRAINT fk_sat_customer_contact_hub_customer FOREIGN KEY (customer_hk) REFERENCES hub_customer (customer_hk))
;

